/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './*.html',
    './404.html',
    './en/**/*.html',
    './vi/**/*.html',
    './blog-archived/**/*.{html,js}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#595c5e',
        'surface-bright': '#f5f7fa',
        'primary-fixed-dim': '#8486ff',
        'tertiary-fixed': '#fdb64b',
        'secondary-container': '#94f991',
        'error-dim': '#a70138',
        primary: '#4546d7',
        'inverse-primary': '#8083ff',
        'on-primary': '#f4f1ff',
        'tertiary-dim': '#6f4700',
        'primary-fixed': '#9396ff',
        secondary: '#006b1c',
        'on-primary-container': '#0b0081',
        outline: '#74777a',
        'secondary-fixed-dim': '#87eb85',
        'tertiary-container': '#fdb64b',
        'on-error-container': '#510017',
        'on-primary-fixed': '#000000',
        'on-surface': '#2c2f32',
        'inverse-surface': '#0b0f11',
        'secondary-fixed': '#94f991',
        'error-container': '#f74b6d',
        surface: '#f5f7fa',
        'primary-dim': '#3837cb',
        'on-background': '#2c2f32',
        'surface-variant': '#d9dde1',
        'on-secondary-fixed': '#004a11',
        'on-secondary-container': '#006018',
        'surface-container': '#e5e8ec',
        'tertiary-fixed-dim': '#eda93f',
        'on-secondary': '#d1ffc9',
        'on-tertiary': '#fff0e2',
        'surface-container-low': '#eef1f4',
        'on-tertiary-container': '#573800',
        'surface-tint': '#4546d7',
        'secondary-dim': '#005d17',
        'on-error': '#ffefef',
        'surface-container-high': '#dfe3e7',
        'on-tertiary-fixed': '#3c2500',
        'surface-container-highest': '#d9dde1',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#0f009c',
        tertiary: '#7e5200',
        error: '#b41340',
        'surface-dim': '#d0d5d9',
        'outline-variant': '#abadb0',
        'on-secondary-fixed-variant': '#006b1c',
        'inverse-on-surface': '#9a9da0',
        background: '#f5f7fa',
        'primary-container': '#9396ff',
        'on-tertiary-fixed-variant': '#634000',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
